Anuncio2/Controllers/PessoasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Dominio;
using RepositorioEF;

namespace Anuncio2
{
    public class PessoasController : Controller
    {
        private ProjetoEstudoContex db = new ProjetoEstudoContex();

        [Authorize]
        // GET: Pessoas
        public ActionResult Index()
        {
            
            return View();
        }
                

        [Authorize]
        // GET: Pessoas/Details/5
        public ActionResult Details()
        {
                      
            var indice = db.Pessoas.Where(x => x.Email == User.Identity.Name).FirstOrDefault();

            if (indice == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pessoa pessoa = db.Pessoas.Find(indice.ID);
            if (pessoa == null)
            {
                return HttpNotFound();
            }
            return View(pessoa);
        }


        [AllowAnonymous]
        // GET: Pessoas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Pessoas/Create
        // Para proteger-se contra ataques de excesso de postagem, ative as propriedades específicas às quais deseja se associar. 
        // Para obter mais detalhes, confira https://go.microsoft.com/fwlink/?LinkId=317598.
        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Nome,Email,Senha,ConfirmarSenha")] Pessoa pessoa)
        {
            var p = db.Pessoas.Where(x => x.Email == pessoa.Email).FirstOrDefault();
            if (p != null)
            {
                ModelState.AddModelError("Email", "Email já existe");
            }

            if (ModelState.IsValid)
            {
                db.Pessoas.Add(pessoa);
                db.SaveChanges();
                FormsAuthentication.SetAuthCookie(pessoa.Email, false);
                return RedirectToAction("Index","Anuncios");
            }

            return View(pessoa);
        }

        [Authorize]
        // GET: Pessoas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pessoa pessoa = db.Pessoas.Find(id);
            if (pessoa == null)
            {
                return HttpNotFound();
            }
            return View(pessoa);
        }

        // POST: Pessoas/Edit/5
        // Para proteger-se contra ataques de excesso de postagem, ative as propriedades específicas às quais deseja se associar. 
        // Para obter mais detalhes, confira https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Nome,Email,Senha,ConfirmarSenha")] Pessoa pessoa)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pessoa).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pessoa);
        }

        [Authorize]
        // GET: Pessoas/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Pessoa pessoa = db.Pessoas.Find(id);
        //    if (pessoa == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(pessoa);
        //}

        //[Authorize]
        //// POST: Pessoas/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Pessoa pessoa = db.Pessoas.Find(id);
        //    db.Pessoas.Remove(pessoa);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        [Authorize]
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Login(Pessoa login, string returnUrl)
        {          
                var pessoa = db.Pessoas.Where(x => x.Email == login.Email).FirstOrDefault();
                if (pessoa != null)
                {
                    if (pessoa.Senha == login.Senha)
                    {
                        FormsAuthentication.SetAuthCookie(login.Email, false);
                        if (Url.IsLocalUrl(returnUrl))
                        {
                            return Redirect(returnUrl);
                        }
                        else
                        {
                            return RedirectToAction("Index", "Anuncios");
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("Senha", "Senha Invalida.");
                    }

                }
                else
                {
                    ModelState.AddModelError("", "Login inválido.");
                }
              

            return View(login);
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult LogOff()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Anuncios");
        }

    }
}

Anuncio2/Views/Pessoas/Create.cshtml
@model Dominio.Pessoa

@{
    ViewBag.Title = "Create";
}


<div class="container cadastro">
    @using (Html.BeginForm("Create", "Pessoas", FormMethod.Post, new { @class = "form-signin", role = "form" }))
    {
        @Html.AntiForgeryToken()

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "" })
            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nome" } })
            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "" })
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @placeholder = "Email" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Senha, htmlAttributes: new { @class = "" })
            @Html.PasswordFor(model => model.Senha, new { @class = "form-control", @placeholder = "Senha" } )
            @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmarSenha, htmlAttributes: new { @class = "" })
            @Html.PasswordFor(model => model.ConfirmarSenha, new { @class = "form-control", @placeholder = "ConfirmarSenha" })
            @Html.ValidationMessageFor(model => model.ConfirmarSenha, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">            
                <input type="submit" value="Salvar" class="btn btn-default" />           
        </div>

    }
</div>

   

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

Anuncio2/Views/Pessoas/Delete.cshtml
@model Dominio.Pessoa

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pessoa</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Senha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Senha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ConfirmarSenha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConfirmarSenha)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Anuncio2/Views/Pessoas/Details.cshtml
@model Dominio.Pessoa

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Pessoa</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar Senha", "Edit", new { id = Model.ID }) 
</p>

Anuncio2/Views/Pessoas/Edit.cshtml
@model Dominio.Pessoa

@{
    ViewBag.Title = "Edit";
}

<div class="container cadastro">
    @using (Html.BeginForm(Html.BeginForm("Edit", "Pessoas", FormMethod.Post, new { @class = "form-signin", role = "form" })))    {
        @Html.AntiForgeryToken()
       
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID)

            <div class="form-group">
                @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })               
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })               
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Senha, htmlAttributes: new { @class = "" })
                @Html.PasswordFor(model => model.Senha,  new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })                
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ConfirmarSenha, htmlAttributes: new { @class = "" })
                @Html.PasswordFor(model => model.ConfirmarSenha, new {  @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.ConfirmarSenha, "", new { @class = "text-danger" })             
            </div>

            <div class="form-group">                
                    <input type="submit" value="Salvar" class="btn btn-default" />                
            </div>
       
    }
</div>
   
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

Anuncio2/Views/Pessoas/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

Anuncio2/Views/Pessoas/Login.cshtml
@model Dominio.Pessoa

@{ ViewBag.Title = "Login"; }
<div class="container cadastro">
    <section id="loginForm">
        @using (Html.BeginForm("Login", "Pessoas", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-signin", role = "form" }))
        {
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <h2 class="form-signin-heading">Acesse a sua Conta</h2>

            <div class="form-group">
                @Html.LabelFor(m => m.Email, new { @class = "sr-only" })
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control", @placeholder = "Email" })
                @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Senha, new { @class = "sr-only" })
                @Html.PasswordFor(m => m.Senha, new { @class = "form-control", @placeholder = "Senha" })
                @Html.ValidationMessageFor(m => m.Senha, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <input type="submit" class="btn btn-lg btn-primary btn-block" value="Entrar" />
            </div>
            <br />
            <label class="entrarCadastro">Não tem uma conta? @Html.ActionLink("Cadastre-se", "Create", "Pessoas") </label>
        }

    </section>
    </div>


@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}